import { useState } from "react";
import Papa from "papaparse";
import { jsPDF } from "jspdf";

export default function Home() {
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState([]);
  const [result, setResult] = useState("");
  const [metadata, setMetadata] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  // Handle CSV file change and generate preview
  const handleFileChange = (e) => {
    const f = e.target.files[0];
    setFile(f);
    setError("");
    setResult("");
    setMetadata(null);

    if (!f) return;

    Papa.parse(f, {
      header: true,
      preview: 5,
      complete: (results) => setPreview(results.data),
      error: () =>
        setError("Error reading the file. Please check the CSV format."),
    });
  };

  // Handle file submit (analysis)
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!file) return;

    setLoading(true);
    setError("");
    setResult("");
    setMetadata(null);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const res = await fetch("http://127.0.0.1:8000/analyze", {
        method: "POST",
        body: formData,
      });

      if (!res.ok) throw new Error("Server error");
      const data = await res.json();
      setResult(data.summary);
      setMetadata(data.metadata);
    } catch (err) {
      setError(
        "An error occurred while processing the file. Try again with another CSV."
      );
    } finally {
      setLoading(false);
    }
  };

  // Export current analysis to styled PDF
  const handleExportPDF = () => {
    if (!result) {
      alert("Please generate an analysis first.");
      return;
    }

    const doc = new jsPDF({
      orientation: "p",
      unit: "pt",
      format: "a4",
      putOnlyUsedFonts: true,
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 50;
    const textWidth = pageWidth - margin * 2;
    const currentDate = new Date().toLocaleDateString();

    // HEADER background
    doc.setFillColor(26, 60, 122); // deep blue
    doc.rect(0, 0, pageWidth, 80, "F");

    // HEADER text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.setTextColor(255, 255, 255);
    doc.text("DataNarrator Report", margin, 50);

    doc.setFontSize(11);
    doc.text(`Generated on ${currentDate}`, margin, 70);

    // TITLE SECTION
    doc.setTextColor(0, 0, 0);
    doc.setFont("times", "bold");
    doc.setFontSize(18);
    doc.text("Executive Data Analysis", margin, 120);

    // METADATA BLOCK
    if (metadata) {
      doc.setFont("times", "italic");
      doc.setFontSize(11);
      const metaText = `
Dataset Summary:
Rows: ${metadata.rows}
Columns: ${metadata.cols}
Time Column: ${metadata.time_column || "None"}
Numeric Columns: ${
        metadata.numeric_columns?.slice(0, 6).join(", ") || "None"
      }${metadata.numeric_columns?.length > 6 ? ", ..." : ""}
`;
      const splitMeta = doc.splitTextToSize(metaText.trim(), textWidth);
      doc.text(splitMeta, margin, 145);
    }

    // BODY TEXT
    const cleanText = result.replace(/[^\x00-\x7F]/g, ""); // remove emojis
    doc.setFont("times", "normal");
    doc.setFontSize(12);

    const splitText = doc.splitTextToSize(cleanText, textWidth);
    let y = metadata ? 220 : 160;

    splitText.forEach((line) => {
      if (y > pageHeight - 70) {
        // add new page when reaching bottom
        doc.addPage();
        y = margin;
      }
      doc.text(line, margin, y);
      y += 18;
    });

    // FOOTER
    const footer = "Generated by DataNarrator";
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(footer, margin, pageHeight - 30);

    // SAVE
    doc.save("DataNarrator_Executive_Report.pdf");
  };

  // ---------------------------------------------------------------------------
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-950 to-gray-900 text-white flex flex-col items-center justify-center p-6">
      <h1 className="text-4xl font-bold text-blue-400 mb-2">📊 DataNarrator</h1>
      <p className="text-gray-400 mb-6 text-center max-w-md">
        Upload a CSV file to generate a statistically verified executive
        analysis.
      </p>

      <form onSubmit={handleSubmit} className="flex flex-col items-center gap-4">
        <input
          type="file"
          accept=".csv"
          onChange={handleFileChange}
          className="text-gray-300 bg-gray-800 px-3 py-2 rounded-md"
        />

        {loading ? (
          <div className="flex flex-col items-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mb-2"></div>
            <p className="text-sm text-gray-400">Analyzing data...</p>
          </div>
        ) : (
          <button
            type="submit"
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 px-5 py-2 rounded-md transition-colors"
          >
            Submit CSV
          </button>
        )}
      </form>

      {error && (
        <div className="bg-red-900/50 border border-red-600 mt-6 px-4 py-3 rounded-md max-w-md text-sm text-red-300">
          {error}
        </div>
      )}

      {preview.length > 0 && (
        <div className="max-w-2xl bg-gray-900 p-4 rounded-md shadow mt-6 text-sm overflow-x-auto">
          <h3 className="text-blue-400 font-semibold mb-2">File preview:</h3>
          <table className="table-auto w-full text-left border-collapse border border-gray-700">
            <thead>
              <tr>
                {Object.keys(preview[0]).map((key) => (
                  <th key={key} className="border border-gray-700 px-2 py-1">
                    {key}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {preview.map((row, i) => (
                <tr key={i}>
                  {Object.values(row).map((val, j) => (
                    <td
                      key={j}
                      className="border border-gray-800 px-2 py-1 truncate max-w-[100px]"
                    >
                      {val}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {result && (
        <div className="max-w-2xl bg-gray-900 p-4 rounded-md shadow mt-8 text-justify">
          <h2 className="text-xl mb-2 font-semibold text-blue-400">
            Executive Analysis:
          </h2>
          <p>{result}</p>

          <button
            onClick={handleExportPDF}
            className="bg-green-600 hover:bg-green-700 px-4 py-2 rounded-md mt-4 transition-colors"
          >
            Export PDF
          </button>
        </div>
      )}

      <footer className="mt-10 text-sm text-gray-500">
        Developed by{" "}
        <a
          href="https://github.com/EnricoMann"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-400 hover:underline"
        >
          Enrico Mann
        </a>
      </footer>
    </div>
  );
}
